name: wallet-app
services: 
  wallet-service-debug:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.debug
    image: wallet-service-debug:latest
    command: >
      dlv debug ./cmd/app
      --headless --listen=0.0.0.0:40000
      --api-version=2 --accept-multiclient 
      --output=/app/bin/debug
    ports:
      - 40000:40000
    volumes:
      - ./../:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    profiles: ["debug"]

  wallet-service-test:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.test
    image: wallet-service-test:latest
    command: > 
      go test -tags=integration ./...
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    profiles: ["test"]

  wallet-service-release:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.release
    image: wallet-service-release:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    profiles: ["release"]

  db:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - ./../.env
    profiles: ["debug", "release"]

volumes:
  postgres_data: