name: wallet-app
services: 
  wallet-service-debug:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.debug
    image: wallet-service-debug:latest
    command: >
      dlv debug ./cmd/app
      --headless --listen=0.0.0.0:${WALLET_APP_DEBUG_PORT}
      --api-version=2 --accept-multiclient 
      --output=/app/bin/debug
    ports:
      - ${WALLET_APP_DEBUG_PORT}:${WALLET_APP_DEBUG_PORT}
      - ${WALLET_APP_PORT}:${WALLET_APP_PORT}
    volumes:
      - ./../:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    profiles: ["debug"]

  wallet-service-test:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.testing
    image: wallet-service-test:latest
    working_dir: /app
    command: > 
      go test -tags=integration,unit ./...
    volumes:
      - ./../:/app
    env_file:
      - ./../.env
    profiles: ["test"]

  wallet-service-release:
    build:
      context: ./..
      dockerfile: ./build/Dockerfile.release
    image: wallet-service-release:latest
    command: > 
      /app/app
    ports:
      - ${WALLET_APP_PORT}:${WALLET_APP_PORT}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../.env
    profiles: ["release"]

  db:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - ./../.env
    profiles: ["debug", "release"]

volumes:
  postgres_data: